apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: {{ .Values.postgresql-db.namespace }}
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>