apiVersion: v1
kind: Service
metadata:
  name: sql-service
  namespace: {{ .Values.postgresql-db.namespace }}
spec:
  selector:
    app: sql-database
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql-db.service.port }}
      targetPort: {{ .Values.postgresql-db.service.port }}