apiVersion: v1
kind: Namespace
metadata:
  name: database-ns

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql-db.statefulset.db-sts-Name }}
  namespace: database-ns
spec:
  serviceName: {{ .Values.postgresql-db.service.postgresqlServiceName }}
  replicas: {{ .Values.postgresql-db.statefulset.replicas }}
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: sql-container
          image: {{ .Values.postgresql-db.statefulset.image }}
          env:
            - name: {{ .Values.postgresql-db.secret.postgresqlPassword }}
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          ports:
            - containerPort: {{ .Values.postgresql-db.service.postgresqlPort }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.postgresql-db.statefulset.storage.VolumeClaimName }}
      spec:
        accessModes: {{ .Values.postgresql-db.statefulset.storage.accessModes | toYaml | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.postgresql-db.statefulset.storage.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql-db.statefulset.storage.VolumeClaimName }}
  namespace: database-ns
spec:
  accessModes:
    - {{ .Values.postgresql-db.statefulset.storage.accessModes | toYaml | nindent 8 }}
  resources:
    requests:
      storage: {{ .Values.postgresql-db.statefulset.storage.size }}