apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.redis.namespace }}
spec:
  replicas: {{ .Values.redis.deployment.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.deployment.image }}
          ports:
            - containerPort: {{ .Values.redis.service.port }}