apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ .Values.redis.namespace }}
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>