nginx:
  enabled: true
  namespace: nginx_server-ns

  configmap:
    name: configmap

  secrets:
    nginx-tls-secret:
      secretName: 
      dataKey: tls.crt 
    nginx_app-ingress-tls-secret:
      secretName: 
      dataKey: tls.crt 

  service:
    annotations: {}
    namespace: nginx_server-ns
    name: nginx-svc
    port: 80

  deployment:
    namespace: nginx_server-ns
    name: nginx-depl
    replicas: 2
    image: nginx:1.25