apiVersion: v1
kind: Secret
metadata:
  name: ingress-credentials
  namespace: {{ .Values.ingress.namespace }}
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>