apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.service.name }}
  namespace: {{ .Values.ingress.namespace }}
spec:
  selector:
    app: ingress-controller
  ports:
    - port: {{ .Values.ingress.service.containerPort1 }}
      targetPort: {{ .Values.ingress.service.containerPort1 }}
    - port: {{ .Values.ingress.service.containerPort2 }}
      targetPort: {{ .Values.ingress.service.containerPort2 }}