apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
    scrape_configs:
      - job_name: 'nginx'
        static_configs:
          - targets: [{{ .Values.prometheus.targets | join ", " }}]