apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.deployment.name }}
  namespace: {{ .Values.prometheus.namespace }}
spec:
  replicas: {{ .Values.prometheus.deployment.replicas }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.deployment.image }}
          ports:
            - containerPort: {{ .Values.prometheus.service.port }}