apiVersion: v1
kind: Secret
metadata:
  name: prom-credentials
  namespace: {{ .Values.prometheus.namespace }}
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>