apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
  namespace: {{ .Values.prometheus.namespace }}
spec:
  selector:
    app: prom
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}