apiVersion: v1
kind: Namespace
metadata:
  name: backup-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k10
  namespace: backup-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasten-io
  template:
    metadata:
      labels:
        app: kasten-io
    spec:
      containers:
        - name: k10
          image: kasten/k10:latest
          ports:
            - containerPort: 8080
          env:
            - name: K10_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---

apiVersion: v1
kind: Service
metadata:
  name: k10-service
  namespace: backup-ns
spec:
  selector:
    app: kasten-io
  ports:
    - port: 8080
      targetPort: 8080
