apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kasten.deployment.name }}
  namespace: {{ .Values.kasten.namespace }}
spec:
  replicas: {{ .Values.kasten.deployment.replicas }}
  selector:
    matchLabels:
      app: kasten-io
  template:
    metadata:
      labels:
        app: kasten-io
    spec:
      containers:
        - name: k10
          image: {{ .Values.kasten.deployment.image }}
          ports:
            - containerPort: {{ .Values.kasten.service.port }}