apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kasten.service.name }}
  namespace: {{ .Values.kasten.namespace }}
spec:
  selector:
    app: kasten-io
  ports:
    - port: {{ .Values.kasten.service.port }}
      targetPort: {{ .Values.kasten.service.port }}