apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fluent-bit.deployment.name }}
  namespace: {{ .Values.fluent-bit.namespace }}
spec:
  replicas: {{ .Values.fluent-bit.deployment.replicas }}
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      containers:
        - name: fluentbit
          image: {{ .Values.fluent-bit.deployment.image }}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
          resources:
            limits:
              memory: 200Mi
      volumes:
        - name: config
          configMap:
            name: fluentbit-config
