apiVersion: v1
kind: Secret
metadata:
  name: logging-credentials
  namespace: {{ .Values.fluent-bit.namespace }}
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>