postgresql-db:
  enabled: true
  namespace: database-ns

  postgresqlUsername: POSTGRESQL_ROOT_USERNAME
  postgresqlPassword: POSTGRESQL_ROOT_PASSWORD
  postgresqlDatabase: my-db

  configmap:
    postgresqlConfigMap:
      postgresql-config: # |
        # # PostgreSQL configuration
        # max_connections = 100
        # shared_buffers = 2GB
        # effective_cache_size = 4GB
        # maintenance_work_mem = 256MB
        # checkpoint_completion_target = 0.9
        # wal_buffers = 16MB
        # default_statistics_target = 100
        # random_page_cost = 1.1
        # effective_io_concurrency = 200
        # work_mem = 5242kB
        # min_wal_size = 1GB
        # max_wal_size = 2GB

  secret:
    postgresqlSecret:
      postgresqlPassword: POSTGRESQL_ROOT_PASSWORD

  service:
    name: sql-service
    port: 3306

  statefulset:
    name: postgresql
    replicas: 2
    image: bitnami/postgresql:12.0.0
    storage:
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      VolumeClaimName: db-pvc