apiVersion: v1
kind: Secret
metadata:
  name: nginx-credentials
  namespace: {{ .Values.nginx.namespace }}
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>